### ISSUE TITLE
onAllStoriesEnd issue

### ISSUE THREAD

**Issue by likx2** [mohitk05/react-insta-stories#130]
The Stories component is in the modal. The problem is that after ending of all stories  in  onAllStoriesEnd prop I pass the function that update state to unmount the component (close the modal window) and get the error like this https://github.com/mohitk05/react-insta-stories/issues/85 . But using simple close button that doing the same (updating state to close the modal) is ok.

**Comment by codewickz** [comment]
I have multiple users having stories and corresponding buttons for viewing stories, but each of them is not even opening after adding onAllStoriesEnd

            <Stories 
            stories={userStories} 
            defaultInterval={5000} 
            width={432} 
            height={700}
            keyboardNavigation={true}
            onAllStoriesEnd={router.push("/")}
            />

**Comment by mohitk05** [comment]
I checked this - currently, the `allStoriesEndCallback` is called synchronously and a few state update functions are called right after it. So if you unmount the component in the callback, the state update calls will throw an error. As a solution, I'm adding a ref value to maintain the mounted state of `Container` class, **you can update to `v2.2.1` where the issue is resolved**.

Maybe a better way would be to make the callback return a Promise and the state update calls will only happen after the Promise is resolved, but that would be a breaking change. I'll consider that in the next major release, let me know if you are aware of any other better way of doing this!
