### ISSUE TITLE
New prop to prevent first story from autostart

### ISSUE THREAD

**Issue by sebastianomiotek** [mohitk05/react-insta-stories#146]
Is it possible to achieve a manual block autostart of the first story? Or can it be achieved with props? Unfortunately, after using 'useEffect' and `action('pause')` it doesn't work. Works with setTimeout 0 but I wanted to avoid it: D

Goal to be achieved:
I don't want the first story to start because I have an embedded video file that needs some buffering time. Only after buffering is finished and the video has been started, I would like to start a story playing (+ the bar at the top starts going from left to right). Is something like this planned?

**Comment by mohitk05** [comment]
Hey, yes it is possible but you might have to write a custom renderer for this. Currently, to remain backwards compatible, all default renderers (image, video) are wrapped in a HOC that autoplays the story on mount. Refer: https://github.com/mohitk05/react-insta-stories/blob/master/src/renderers/AutoPlayContent.tsx

Your solution would be to pass a prop named `renderers=[CustomVideo]`. The `CustomVideo` is a file that exports two things: `renderer` which is a React component and `tester` which is a function that returns an object as described [here](https://github.com/mohitk05/react-insta-stories#renderers). You can set the priority high enough so that your renderer is used. In your `renderer` you can do the custom thing that you want, the story won't autostart there.

Something like:

```js
// CustomVideo.js
export const renderer = ({ story, action, isPaused, config }) => {
        const onLoad = () => {
            action('play');
        }
	return <div>
            <video onLoad={onLoad} src="video.mp4"></video>
        </div>;
};

export const tester = (story) => {
	return {
		condition: story.type === 'video',
		priority: 3,
	};
};
```
