### ISSUE TITLE
Cors problem while rendering a photo

### ISSUE THREAD

**Issue by yuvalbader** [mohitk05/react-insta-stories#252]
Hello, I am having Cors problem.
I have an array of stories that I build dynamically, the stories combine photos and videos.
For some reason when I pass a url of a video it is rendered properly and everything is fine. But when I pass an image url, it doesn't render it properly and I get a default broken image icon. Elsewhere in the application I found that the solution is to put crossOrigin="anonymous" in the img tag, but in the Stories component I have no way to add it.
In addition,  when I access the url of the image directly through the browser, it is displayed properly without a problem, therefore the problem is not in the url.
Thank you

**Comment by yuvalbader** [comment]
Hi, Is there anyone here who can help me?

**Comment by mohitk05** [comment]
Hey @yuvalbader, this is an expected behaviour in the browser. Adding a crossorigin anonymous attribute by default would not be a good solution for this.
The error suggests that the service providing the image does not allow access from your origin. Usually, CDNs do not have this problem. If you have control over the service, you should add your origin to the allowed set of origins.
